---
deployment:
    tasks:
        - export DEPLOYPATH=/home/mikeqsgc/skeeballworldtour
        - /bin/cp -R /client/build $DEPLOYPATH
        - /bin/cp /config/pool.js $DEPLOYPATH
        - /bin/cp -R controllers $DEPLOYPATH
        - /bin/cp -R models $DEPLOYPATH
        - /bin/cp -R pdf $DEPLOYPATH
        - /bin/cp package.json $DEPLOYPATH
		- /bin/cp server.js $DEPLOYPATH
