---
deployment:
    tasks:
        - export DEPLOYPATH=/home/mikeqsgc/skeeballworldtour/
        - /bin/cp -R controllers $DEPLOYPATH
        - /bin/cp -R models $DEPLOYPATH
        - /bin/cp -R pdf $DEPLOYPATH
        - /bin/cp -R package.json $DEPLOYPATH
        - /bin/cp -R server.js $DEPLOYPATH
        - export DEPLOYPATHCLIENT=/home/mikeqsgc/skeeballworldtour/client/build/
        - /bin/cp -r ./client/build $DEPLOYPATHCLIENT
        - export DEPLOYPATHCONFIG=/home/mikeqsgc/skeeballworldtour/config/
        - /bin/cp ./config/pool.js $DEPLOYPATHCONFIG
        - /bin/mkdir /home/mikeqsgc/skeeballworldtour/test
