---
deployment:
    tasks:
        - export DEPLOYPATH=/home/mikeqsgc/skeeballworldtour.mikegullo.com/
        - /bin/rm -rf ${DEPLOYPATH}/admin
        - /bin/rm -rf ${DEPLOYPATH}/client
        - /bin/rm -rf ${DEPLOYPATH}/config
        - /bin/rm -rf ${DEPLOYPATH}/controllers
        - /bin/rm -rf ${DEPLOYPATH}/models
        - /bin/rm -rf ${DEPLOYPATH}/pdf
        - /bin/rm -rf ${DEPLOYPATH}/passport
        - /bin/cp -r controllers $DEPLOYPATH
        - /bin/cp -r models $DEPLOYPATH
        - /bin/cp -r pdf $DEPLOYPATH
        - /bin/cp -r passport $DEPLOYPATH
        - /bin/cp package.json $DEPLOYPATH
        - /bin/cp server.js $DEPLOYPATH
        - /bin/mkdir ${DEPLOYPATH}/admin
        - /bin/mkdir ${DEPLOYPATH}/client
        - /bin/cp -r ./admin/build ${DEPLOYPATH}/admin
        - /bin/cp -r ./client/build ${DEPLOYPATH}/client
        - /bin/mkdir ${DEPLOYPATH}/config
        - /bin/cp ./config/connectionPool.js ${DEPLOYPATH}/config
