---
deployment:
    tasks:
        - export DEPLOYPATH=/home/mikeqsgc/skeeballworldtour
        - /bin/cp -R client/build /home/mikeqsgc/skeeballworldtour/client
        - /bin/cp -R config/pool.js /home/mikeqsgc/skeeballworldtour/config
        - /bin/cp -R controllers $DEPLOYPATH
        - /bin/cp -R models $DEPLOYPATH
        - /bin/cp -R pdf $DEPLOYPATH
        - /bin/cp -R package.json $DEPLOYPATH
        - /bin/cp -R server.js $DEPLOYPATH
